drop table gls_buyer_agent;
drop table gls_certifications;
drop table gls_config;

drop table gls_bidding;
drop table gls_bidding_product_pic;
drop table gls_bidding_record;
drop table gls_bidding_users;
drop table gls_creditcheck;
drop table gls_dockingproduction;
drop table gls_equipment;
drop table gls_file;             
drop table gls_grouporder_invite;  
drop table gls_grouporder_join;    
drop table gls_grouporder_price;   
drop table gls_grouporder_skuprice;
drop table gls_insidedistribution;
drop table gls_language;
drop table gls_message;
drop table gls_money;
drop table gls_operation_handle;
drop table gls_operation_post;
drop table gls_order_load;
drop table gls_order_logistics;
drop table gls_order_docking;
drop table gls_order_attr;
drop table gls_order_paymant;
drop table gls_order_person;
drop table gls_order_qa;
drop table gls_order_skuprice;
drop table gls_order_stream;
drop table gls_order_streamfile;
drop table gls_order_tracking;
drop table gls_orderitem;
drop table gls_parameter;
drop table gls_parameter_product;
drop table gls_picture;
drop table gls_platform;
drop table gls_protocol;
drop table gls_purchaseorder;
drop table gls_risk_business;
drop table gls_risk_company;
drop table gls_search;
drop table gls_statis_user;
drop table gls_supplier;
drop table gls_user_config;
drop table gls_user_experience;
drop table gls_vendor_sku;
drop table gls_video;
drop table gls_video_log;
drop table gls_video_users;


rename table gls_comment_buyer to comment_buyer;       
rename table gls_comment_local to comment_local;       
rename table gls_comment_supplier to comment_supplier; 
rename table gls_users_bigdata to user_bigdata;
rename table gls_customer_file to customer_file;    
rename table gls_distribution_ratio to distribution_ratio; com.platform.basement.controller.MainController;

 CREATE TABLE `gls_localconsultant` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `userId` int(20) DEFAULT NULL,
  `industry` varchar(50) DEFAULT NULL,
  `industry2` varchar(50) DEFAULT NULL,
  `mainProductCode` varchar(50) DEFAULT NULL,
  `mainProductCode2` varchar(50) DEFAULT NULL,
  `productExp` varchar(50) DEFAULT NULL,
  `productExp2` varchar(50) DEFAULT NULL,
  `is_deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除标识,0.可用，1.已删除不可用',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=331 DEFAULT CHARSET=utf8
gls_localconsultant 是否 local_advisor合并


alter table check_bidding modify dealTime timestamp not null default current_timestamp comment '查看时间';
alter table check_order modify dealTime timestamp not null default current_timestamp comment '查看时间';
alter table contact modify birthday timestamp not null default current_timestamp comment '生日    ';
alter table district modify create_time timestamp not null default current_timestamp comment '添加时间';
alter table district modify update_time timestamp not null default current_timestamp comment '最后修改时间';
alter table email_content modify sent_date timestamp not null default current_timestamp comment '发送日期';
alter table evaluates modify evaluate_startDate timestamp not null default current_timestamp comment '创建时间';
alter table fund_percent modify changeTime timestamp not null default current_timestamp comment '改变比例的时间';
alter table logininfo modify LOGINTIME timestamp not null default current_timestamp comment '登入时间';
alter table `order` modify last_date timestamp not null default current_timestamp comment '最迟装船日';
alter table order_product modify delivery timestamp not null default current_timestamp comment '交货时间';
alter table order_schedule modify trace_ate timestamp not null default current_timestamp comment '下一状态预计时间/物流到达目的地时间';
alter table product modify create_date timestamp not null default current_timestamp comment '录入时间';
alter table product modify up_time timestamp not null default current_timestamp comment '上架时间';
alter table product modify down_time timestamp not null default current_timestamp comment '下架时间';
alter table quote modify quote_date timestamp not null default current_timestamp comment '报价时间';
alter table quote_product modify quote_validity timestamp not null default current_timestamp comment '报价有效期';
alter table supplier_relationship modify create_date timestamp not null default current_timestamp comment '录入时间';
alter table to_manage_bidding modify dealTime timestamp not null default current_timestamp comment '查看竞标管理时间';
alter table trade_record modify dealTime timestamp not null default current_timestamp comment '交易时间';
alter table admin                    modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table bank_account             modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table comment_buyer            modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table comment_local            modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table comment_supplier         modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table customer                 modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table customer_file            modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_auth           modify decision_time            timestamp not null default current_timestamp comment '决策时间,授信通过时间';
alter table financing_auth           modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_auth_invoice   modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_auth_record    modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_check          modify pay_time                 timestamp not null default current_timestamp comment '支付时间，支付成功回调更新';
alter table financing_check          modify push_time                timestamp not null default current_timestamp comment '推送时间';
alter table financing_check          modify approve_time             timestamp not null default current_timestamp comment '批复时间';
alter table financing_check          modify confirm_time             timestamp not null default current_timestamp comment '确认时间';
alter table financing_check          modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_file           modify issue_date               timestamp not null default current_timestamp comment '签发日期';
alter table financing_file           modify end_date                 timestamp not null default current_timestamp comment '到期日期';
alter table financing_file           modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_file_100       modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_file_101       modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_file_102       modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_file_103       modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_file_104       modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_file_105       modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_file_106       modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_file_107       modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_file_302       modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_file_402       modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_file_type      modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_order          modify shipment_date            timestamp not null default current_timestamp comment '装船日';
alter table financing_order          modify receipt_date             timestamp not null default current_timestamp comment '接收时间';
alter table financing_order          modify approve_time             timestamp not null default current_timestamp comment '批复时间';
alter table financing_order          modify receipt_account_date     timestamp not null default current_timestamp comment '应收到账日期';
alter table financing_order          modify check_invoice_date       timestamp not null default current_timestamp comment '审单日期';
alter table financing_order          modify check_invoice_pass_date  timestamp not null default current_timestamp comment '审单通过日期';
alter table financing_order          modify loan_date                timestamp not null default current_timestamp comment '放款日期';
alter table financing_order          modify rece_date                timestamp not null default current_timestamp comment '还款日期';
alter table financing_order          modify compensate_date          timestamp not null default current_timestamp comment '赔付日期';
alter table financing_order          modify final_payment_date       timestamp not null default current_timestamp comment '尾款结算日';
alter table financing_order          modify buyer_confirm_date       timestamp not null default current_timestamp comment '买家确认时间';
alter table financing_order          modify payment_date             timestamp not null default current_timestamp comment '结算操作时间';
alter table financing_order          modify contract_sign_time       timestamp not null default current_timestamp comment '合同签订时间';
alter table financing_order          modify contract_create_time     timestamp not null default current_timestamp comment '合同签约时间';
alter table financing_order          modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_payment        modify apply_date               timestamp not null default current_timestamp comment '申请用款时间';
alter table financing_payment        modify pay_time                 timestamp not null default current_timestamp comment '放款时间';
alter table financing_payment        modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table financing_payment_detail modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table menu                     modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table order_invoice            modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table order_invoice_bg         modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table order_invoice_fp         modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table order_invoice_fp_detail  modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table order_invoice_td         modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table order_invoice_ycdz       modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table order_invoice_yh         modify email_time               timestamp not null default current_timestamp comment '邮件时间';
alter table order_invoice_yh         modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table order_invoice_zxd        modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table order_invoice_zxd_detail modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table pay_bill                 modify bill_date                timestamp not null default current_timestamp comment '账单生成时间，提现时间';
alter table pay_bill                 modify pay_time                 timestamp not null default current_timestamp comment '支付时间';
alter table pay_bill                 modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table pay_bill_detail          modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table pay_order                modify pay_time                 timestamp not null default current_timestamp comment '支付时间';
alter table pay_order                modify end_time                 timestamp not null default current_timestamp comment '到期时间';
alter table pay_order                modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table pay_order_commission     modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table port                     modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table quote_updatelog          modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table role_menu                modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table role_user                modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table roles                    modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table roles                    modify date_time                timestamp not null default current_timestamp comment '用户创建时间';
alter table service_company_config   modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table service_push_log         modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table sku                      modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table sku_pro                  modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table sku_provalue             modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table supplier_check           modify ex_check_date            timestamp not null default current_timestamp comment '期望审厂日期';
alter table supplier_check           modify check_date               timestamp not null default current_timestamp comment '实际审厂日期';
alter table supplier_check           modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table supplier_device          modify product_time             timestamp not null default current_timestamp comment '生产时间';
alter table supplier_device          modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table supplier_image           modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table supplier_report          modify issue_date               timestamp not null default current_timestamp comment '签发日期';
alter table supplier_report          modify end_date                 timestamp not null default current_timestamp comment '到期日期';
alter table supplier_report          modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table tms_confirm              modify ccdate                   timestamp not null default current_timestamp comment '截关日期y';
alter table tms_confirm              modify cydate                   timestamp not null default current_timestamp comment '截重柜时间y预计截载时间';
alter table tms_confirm              modify cfdate                   timestamp not null default current_timestamp comment '截补料时间y';
alter table tms_confirm              modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table tms_confirm_price        modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table tms_order                modify pickup_date              timestamp not null default current_timestamp comment '要求装货时间y yyyy-mm-dd';
alter table tms_order                modify delivery_date            timestamp not null default current_timestamp comment '要求到达时间y yyyy-mm-dd';
alter table tms_order                modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table tms_plan                 modify checked_time             timestamp not null default current_timestamp comment '确定订舱方案时间';
alter table tms_plan                 modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table tms_plan_detail          modify etd                      timestamp not null default current_timestamp comment '预计开船日期y预计起飞时间/预计装车日期yyyy-mm-dd';
alter table tms_plan_detail          modify eta                      timestamp not null default current_timestamp comment '预计到港日期y预计到达时间/预计到站日期yyyy-mm-dd';
alter table tms_plan_detail          modify ccdate                   timestamp not null default current_timestamp comment '截关日期y';
alter table tms_plan_detail          modify cydate                   timestamp not null default current_timestamp comment '截重柜时间y预计截载时间';
alter table tms_plan_detail          modify cfdate                   timestamp not null default current_timestamp comment '截补料时间 y';
alter table tms_plan_detail          modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table tms_plan_price           modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table tms_quote                modify quote_time               timestamp not null default current_timestamp comment '报价时间（物流商报价）';
alter table tms_quote                modify checked_time             timestamp not null default current_timestamp comment '确定方案时间（用户选择方案）';
alter table tms_quote                modify create_time              timestamp not null default current_timestamp comment '创建时间';
alter table user_bigdata             modify create_time              timestamp not null default current_timestamp comment '创建时间';
